site_name: Ethereum Execution Spec Tests
site_url: https://execution-spec-tests.readthedocs.io/
copyright: 'Copyright: 2023, Ethereum Community'

nav:
- Home: 'index.md'
- Test Case Descriptions:
  - EIP-4844: 'test_case_descriptions/eip4844.md'
- Getting Started:
  - Quick Start: 'getting_started/quick_start.md'
  - Package Overview: 'getting_started/package_overview.md'
  - Writing Tests: 'getting_started/writing_tests.md'
  - Adding a Reference Spec: 'getting_started/reference_specification.md'
- Tutorials:
  - State Transition Tests: 'tutorials/state_transition.md'

plugins:
  - glightbox

theme: readthedocs

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      toc_depth: 4 
  - admonition