name: Build and Package Fixtures
inputs:
  name:
    description: 'Name of the fixture package'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install yq
      shell: bash
      run: |
        pip install yq
    - name: Extract fixture properties
      id: properties
      shell: bash
      run: |
        echo "evm-type=$(yq --arg feature "${{ inputs.name }}" '.[$feature]."evm-type"' ./config-feature.yaml)" >> "$GITHUB_OUTPUT"
        echo "fill-params=$(yq --arg feature "${{ inputs.name }}" '.[$feature]."fill-params"' ./config-feature.yaml)" >> "$GITHUB_OUTPUT"
        echo "solc=$(yq --arg feature "${{ inputs.name }}" '.[$feature]."solc"' ./config-feature.yaml)" >> "$GITHUB_OUTPUT"
    - uses: ./.github/actions/build-evm
      id: evm-builder
      with:
        type: ${{ steps.properties.outputs.evm-type }}
    - name: Install solc compiler
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then PLATFORM="linux-amd64"; else PLATFORM="macosx-amd64"; fi
        RELEASE_NAME=$(curl https://binaries.soliditylang.org/${PLATFORM}/list.json | jq -r --arg SOLC_VERSION "${{ steps.properties.outputs.solc }}" '.releases[$SOLC_VERSION]')
        wget -O $GITHUB_WORKSPACE/bin/solc https://binaries.soliditylang.org/${PLATFORM}/$RELEASE_NAME
        chmod a+x $GITHUB_WORKSPACE/bin/solc
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
    - name: Run fixtures fill
      shell: bash
      run: |
        pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -e .
        fill -n auto --evm-bin=${{ steps.evm-builder.outputs.evm-bin }} ${{ steps.properties.outputs.fill-params }}
    - name: Create fixtures info file
      shell: bash
      run: |
        echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
        > fixtures/info.txt
    - name: Tar fixtures output
      shell: bash
      run: |
        tar -czvf fixtures_${{ inputs.name }}.tar.gz ./fixtures
    - uses: actions/upload-artifact@v4
      with:
        name: fixtures_${{ inputs.name }}
        path: fixtures_${{ inputs.name }}.tar.gz