name: Build and Package Fixtures

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    tags-ignore:
      - '*@*'
  workflow_dispatch:

jobs:
  features:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.parse.outputs.features }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup yq
        shell: bash
        run: |
          pip install yq
      - name: Parse config-feature.yaml
        id: parse
        shell: bash
        run: |
          echo "features=$(yq -c '[. | to_entries | .[] | {"name": .key} * .value]' ./config-feature.yaml)" >> "$GITHUB_OUTPUT"
  build:
    needs: features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.features.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/build-fixtures
        with:
          name: ${{ matrix.name }}
          evm-type: ${{ matrix.evm-type }}
          fill-params: ${{ matrix.fill-params }}
          python: ${{ matrix.python }}
          solc: ${{ matrix.solc }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: './**'
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true