name: Build and Package Fixtures for a feature

on:
  push:
    branches:
      - main
    tags:
      - '*@v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get feature name
        id: feature-name
        shell: bash
        run: |
          echo name=eip7692 >> "$GITHUB_OUTPUT"
      - name: Get the selected feature configuration from the config-feature.yaml
        id: config-feature-reader
        shell: bash
        run: |
          awk "/^${{ steps.feature-name.outputs.name }}:/{flag=1; next} /^[[:alnum:]]/{flag=0} flag" ./config-feature.yaml \
          | sed 's/ //g' | sed 's/:/=/g' >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/build-fixtures
        with:
          name: ${{ steps.feature-name.outputs.name }}
          evm-type: ${{ steps.config-feature-reader.outputs.evm-type }}
          fill-params: ${{ steps.config-feature-reader.outputs.fill-params }}
          python: ${{ steps.config-feature-reader.outputs.python }}
          solc: ${{ steps.config-feature-reader.outputs.solc }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Draft Pre-release
        uses: softprops/action-gh-release@v2
        with:
          files: './**'
          draft: true
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true